"""
Shared Constants
Common constants used across EFMM-Toll system
"""

# Service Names
RSU_SERVICE_NAME = "efmm-rsu-edge"
VEHICLE_SERVICE_NAME = "efmm-vehicle-obu"
AGGREGATOR_SERVICE_NAME = "efmm-aggregator"
AUDIT_SERVICE_NAME = "efmm-audit-ledger"

# Default Ports
RSU_DEFAULT_PORT = 8001
VEHICLE_DEFAULT_PORT = 8002
AGGREGATOR_DEFAULT_PORT = 8003
AUDIT_DEFAULT_PORT = 8004

# Communication Protocols
V2X_PROTOCOL = "dsrc"
HTTP_PROTOCOL = "http"
HTTPS_PROTOCOL = "https"
WEBSOCKET_PROTOCOL = "ws"

# Token Types
EPHEMERAL_TOKEN = "ephemeral"
SESSION_TOKEN = "session"
PAYMENT_TOKEN = "payment"
FL_TOKEN = "federated_learning"

# Token Durations (seconds)
SHORT_TOKEN_DURATION = 300    # 5 minutes
MEDIUM_TOKEN_DURATION = 1800  # 30 minutes
LONG_TOKEN_DURATION = 3600    # 1 hour

# Privacy Parameters
DEFAULT_EPSILON = 1.0
DEFAULT_DELTA = 1e-5
LOCATION_ANONYMIZATION_RADIUS = 100.0  # meters
PSEUDONYM_ROTATION_INTERVAL = 3600     # seconds

# Federated Learning Parameters
MIN_FL_PARTICIPANTS = 3
MAX_FL_PARTICIPANTS = 100
FL_ROUND_TIMEOUT = 300  # seconds
FL_AGGREGATION_THRESHOLD = 0.7

# Payment Parameters
MIN_PAYMENT_AMOUNT = 0.01
MAX_PAYMENT_AMOUNT = 100.0
PAYMENT_CONFIRMATION_TIMEOUT = 30  # seconds

# Sensor Parameters
SENSOR_READING_INTERVAL = 1.0  # seconds
SENSOR_CALIBRATION_INTERVAL = 3600  # seconds
VEHICLE_DETECTION_CONFIDENCE_THRESHOLD = 0.8

# Audit Parameters
AUDIT_BATCH_SIZE = 10
AUDIT_FLUSH_INTERVAL = 30  # seconds
BLOCKCHAIN_BLOCK_SIZE = 10
CONSENSUS_TIMEOUT = 60  # seconds

# System Limits
MAX_MESSAGE_SIZE = 1024 * 1024  # 1MB
MAX_CONCURRENT_CONNECTIONS = 1000
MAX_RETRY_ATTEMPTS = 3
CONNECTION_TIMEOUT = 30  # seconds

# Error Codes
SUCCESS = 0
ERROR_INVALID_INPUT = 1001
ERROR_AUTHENTICATION_FAILED = 1002
ERROR_AUTHORIZATION_FAILED = 1003
ERROR_TOKEN_EXPIRED = 1004
ERROR_TOKEN_INVALID = 1005
ERROR_PAYMENT_FAILED = 1006
ERROR_COMMUNICATION_FAILED = 1007
ERROR_SENSOR_FAILURE = 1008
ERROR_MODEL_FAILURE = 1009
ERROR_CONSENSUS_FAILED = 1010
ERROR_AUDIT_FAILED = 1011

# Status Codes
STATUS_INACTIVE = "inactive"
STATUS_INITIALIZING = "initializing"
STATUS_ACTIVE = "active"
STATUS_ERROR = "error"
STATUS_MAINTENANCE = "maintenance"

# Message Priorities
PRIORITY_LOW = 1
PRIORITY_NORMAL = 2
PRIORITY_HIGH = 3
PRIORITY_CRITICAL = 4

# Encryption Parameters
AES_KEY_SIZE = 256
RSA_KEY_SIZE = 2048
HASH_ALGORITHM = "sha256"

# Geolocation Parameters
EARTH_RADIUS_METERS = 6371000
METERS_PER_DEGREE_LAT = 111000
DEFAULT_GEOFENCE_RADIUS = 1000  # meters

# File Extensions
CONFIG_FILE_EXTENSION = ".yaml"
LOG_FILE_EXTENSION = ".log"
MODEL_FILE_EXTENSION = ".pkl"
DATA_FILE_EXTENSION = ".json"

# Directory Names
CONFIG_DIR = "config"
LOGS_DIR = "logs"
MODELS_DIR = "models"
DATA_DIR = "data"
TEMP_DIR = "temp"

# Environment Variables
ENV_LOG_LEVEL = "EFMM_LOG_LEVEL"
ENV_CONFIG_PATH = "EFMM_CONFIG_PATH"
ENV_DATA_PATH = "EFMM_DATA_PATH"
ENV_SERVICE_HOST = "EFMM_SERVICE_HOST"
ENV_SERVICE_PORT = "EFMM_SERVICE_PORT"
